name: Docker CD

on: [push]

jobs:
  tag:
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build, Tag, Publish Docker
      uses: HurricanKai/Publish-Docker-Github-Action@1.12.1
      env:
        GITHUB_TAG: $GITHUB_SHA
      with:
        name: myDocker/repository
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tagging: true
  deploy:
    runs-on: ubuntu-latest
    container: dtzar/helm-kubectl:2.16.1
    name: Deploy
    needs: tag

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Save DigitalOcean kubeconfig
      uses: digitalocean/action-doctl@v1
      env:
        DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      with:
        args: kubernetes cluster kubeconfig show k8s-1-16-2-do-3-ams3-1579807618969 > $GITHUB_WORKSPACE/.kubeconfig
    - name: 'Deploy'
      run: |
        cd helm
        helm upgrade --kubeconfig $GITHUB_WORKSPACE/.kubeconfig --install image-service . --set=image.tag=b15

