name: Docker CD

on: [push]

jobs:
  tag:
    runs-on: ubuntu-latest
    name: tag

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Docker Login
      env:
        DOCKER_USERNAME: $GITHUB_ACTOR
        DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      run: echo $DOCKER_PASSWORD | docker login docker.pkg.github.com -u $DOCKER_USERNAME --password-stdin

    - name: Build container image
      run: docker build -t docker.pkg.github.com/$(echo $GITHUB_REPOSITORY)/image-service:$(echo ${GITHUB_SHA::8} | head -c7) .
      
    - name: Push image to Docker Hub
      run: docker push docker.pkg.github.com/$(echo $GITHUB_REPOSITORY)/image-service:$(echo ${GITHUB_SHA::8} | head -c7)
  deploy:
    runs-on: ubuntu-latest
    container: dtzar/helm-kubectl:2.16.1
    name: Deploy
    needs: tag

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Save DigitalOcean kubeconfig
      uses: digitalocean/action-doctl@v1
      env:
        DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      with:
        args: kubernetes cluster kubeconfig show k8s-1-16-2-do-3-ams3-1579807618969 > $GITHUB_WORKSPACE/.kubeconfig
    - name: 'Deploy'
      run: |
        cd helm
        helm upgrade --kubeconfig $GITHUB_WORKSPACE/.kubeconfig --install image-service . --set=image.tag=$(echo ${GITHUB_SHA::8} | head -c7)

